# Generated by Django 2.2.10 on 2020-02-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentproblems',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentproblems',
            name='task_id',
            field=models.UUIDField(null=True),
        ),
    ]
