# Generated by Django 2.2.10 on 2020-02-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_auto_20200228_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='order',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
