name: Build docker image for server

on:
  push:
    paths:
      - 'cad_server/requirements.txt'
      - 'cad_server/Dockerfile'
      - '.github/workflows/build_docker.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build docker image (with cache) and push it to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: whoan/docker-build-with-cache-action@master
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: qiwihui/codedays
          context: cad_server